apiVersion: apps/v1
kind: Deployment
metadata:
  name: timemachine
  labels:
    app: timemachine
  namespace: namespace-workflow-1699869789748
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timemachine
  template:
    metadata:
      labels:
        app: timemachine
    spec:
      containers:
        - name: timemachine
          image: acrworkflow1699869789748.azurecr.io/image-workflow-1699869789748:latest
          ports:
            - containerPort: 4000