apiVersion: apps/v1
kind: Deployment
metadata:
  name: timemachineback
  labels:
    app: timemachineback
  namespace: namespace-workflow-1699612159275
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timemachineback
  template:
    metadata:
      labels:
        app: timemachineback
    spec:
      containers:
        - name: timemachineback
          image: acrworkflow1699612159275.azurecr.io/image-workflow-1699612159275:latest
          ports:
            - containerPort: 4000