apiVersion: apps/v1
kind: Deployment
metadata:
  name: epitech_timemanager
  labels:
    app: epitech_timemanager
  namespace: namespace-workflow-1699525329296
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epitech_timemanager
  template:
    metadata:
      labels:
        app: epitech_timemanager
    spec:
      containers:
        - name: epitech_timemanager
          image: epitech.azurecr.io/image-workflow-1699525329296:latest
          ports:
            - containerPort: 4000
