apiVersion: v1
kind: Service
metadata:
  name: timemachine
  namespace: namespace-workflow-1699869789748
spec:
  type: LoadBalancer
  selector:
    app: timemachine
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000