apiVersion: v1
kind: Service
metadata:
  name: epitech_timemanager
  namespace: namespace-workflow-1699523294095
spec:
  type: LoadBalancer
  selector:
    app: epitech_timemanager
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000