apiVersion: v1
kind: Service
metadata:
  name: timemachineback
  namespace: namespace-workflow-1699865705247
spec:
  type: LoadBalancer
  selector:
    app: timemachineback
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80