apiVersion: v1
kind: Service
metadata:
  name: timemanageraks
  namespace: namespace-workflow-1699536823239
spec:
  type: LoadBalancer
  selector:
    app: timemanageraks
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
