apiVersion: v1
kind: Service
metadata:
  name: timemachineback
  namespace: namespace-workflow-1699614159648
spec:
  type: LoadBalancer
  selector:
    app: timemachineback
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 4001