apiVersion: v1
kind: Service
metadata:
  name: timemanagerfront
  namespace: namespace-workflow-1699610868765
spec:
  type: LoadBalancer
  selector:
    app: timemanagerfront
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173