apiVersion: v1
kind: Service
metadata:
  name: timemachineback
  namespace: namespace-workflow-1699614159648
spec:
  type: LoadBalancer
  selector:
    app: timemachineback
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000