apiVersion: v1
kind: Service
metadata:
  name: timemachine
  namespace: namespace-workflow-1699869789748
spec:
  type: LoadBalancer
  selector:
    app: timemachine
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 4001