FROM elixir

WORKDIR /app

COPY ../ ./

EXPOSE 8080
EXPOSE 3000
EXPOSE 987
EXPOSE 4000
EXPOSE 5432

RUN apt-get update -y
RUN apt-get install -y inotify-tools

RUN mix local.hex
RUN mix archive.install hex phx_new
RUN mix deps.get

# Installation de PostgreSQL
RUN apt-get install -y postgresql postgresql-contrib

# Configuration de PostgreSQL
USER postgres
RUN /etc/init.d/postgresql start &&\
    psql --command "ALTER USER postgres PASSWORD 'root';" &&\
    createdb -O postgres timemachine_dev
USER root

CMD service postgresql start && mix ecto.create && mix setup && mix phx.server