name: Node.JS Front

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Utilisez la version de Node.js souhaitée

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: cd front && npm i

    - name: Build project
      run: cd front && npm run build

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: front/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: front/dist
